default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: crawler_rebuild_development

test:
  <<: *default
  database: crawler_rebuild_test

production:
  <<: *default
  database: crawler_rebuild_production
  username: deploy
  password: ENV["DB_PASSWORD"]